project_id = "mpewdrpkkkwlpdtgddmn"

[functions.validate-content]
verify_jwt = true

[functions.validate-title]
verify_jwt = true

[functions.academic-advisor]
verify_jwt = true

[functions.generate-article-latex]
verify_jwt = false